### ISSUE TITLE
nightwatch: waitForElementVisible failed on Selenium grid with Firefox

### ISSUE THREAD

**Issue by icloudphil** [expphchen/nightwatch-starter#1]
Chrome works fine as W3C can set to false, but firefox default to use W3C standard.
so the test will failed when using the command such as 

      .waitForElementVisible('#body', 3000)

LOGS:

ℹ Connected to localhost on port 4444 (4666ms).
  Using: firefox (73.0) on linux 4.19.76-linuxkit platform.

Executing the global `beforeEach`
Running:  Github Repositories Navigation

✖ Timed out while waiting for element <#body> to be present for 3000 milliseconds. - expected "visible" but got: "not found" (3221ms)
    at Object.Github Repositories Navigation (/src/git/nightwatch-starter/tests/fixtures/simpleTest.js:5:8)
    at process._tickCallback (internal/process/next_tick.js:68:7) 

FAILED: 1 assertions failed (7.963s)
_________________________________________________

TEST FAILURE:  1 assertions failed, 0 passed (16.85s)

 ✖ simpleTest
 – Github Repositories Navigation (7.963s)
   Timed out while waiting for element <#body> to be present for 3000 milliseconds. - expected "visible" but got: "not found" (3221ms)
       at Object.Github Repositories Navigation (/src/git/nightwatch-starter/tests/fixtures/simpleTest.js:5:8)
       at process._tickCallback (internal/process/next_tick.js:68:7)

npm ERR! code ELIFECYCLE
npm ERR! errno 5
npm ERR! nightwatch-starter@ FF: `nightwatch -e firefox`
npm ERR! Exit status 5
npm ERR! 
npm ERR! Failed at the nightwatch-starter@ FF script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:

**Comment by icloudphil** [comment]
the same test passed on Chrome

**Comment by icloudphil** [comment]
might have to do with create a profile on firefox

**Comment by icloudphil** [comment]
another thread on the mailing list tracking this: https://groups.google.com/forum/#!topic/nightwatchjs/oZyiVdEhc14
